/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CokePagination {
    'currentpage': number;
    'pagesize': number;
    'total': number;
  }
}

declare global {


  interface HTMLCokePaginationElement extends Components.CokePagination, HTMLStencilElement {}
  var HTMLCokePaginationElement: {
    prototype: HTMLCokePaginationElement;
    new (): HTMLCokePaginationElement;
  };
  interface HTMLElementTagNameMap {
    'coke-pagination': HTMLCokePaginationElement;
  }
}

declare namespace LocalJSX {
  interface CokePagination {
    'currentpage'?: number;
    'onPageChanged'?: (event: CustomEvent<any>) => void;
    'pagesize'?: number;
    'total'?: number;
  }

  interface IntrinsicElements {
    'coke-pagination': CokePagination;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'coke-pagination': LocalJSX.CokePagination & JSXBase.HTMLAttributes<HTMLCokePaginationElement>;
    }
  }
}


