/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CokePagination {
    /**
    * The middle name
    */
    'pageSize': number;
    /**
    * The first name
    */
    'totoal': number;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLCokePaginationElement extends Components.CokePagination, HTMLStencilElement {}
  var HTMLCokePaginationElement: {
    prototype: HTMLCokePaginationElement;
    new (): HTMLCokePaginationElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'coke-pagination': HTMLCokePaginationElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface CokePagination {
    /**
    * The middle name
    */
    'pageSize'?: number;
    /**
    * The first name
    */
    'totoal'?: number;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'coke-pagination': CokePagination;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'coke-pagination': LocalJSX.CokePagination & JSXBase.HTMLAttributes<HTMLCokePaginationElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


